- .gitignore
- .user.yml
- macros/tests/tx_block_count.sql
- models/silver/silver__logs.sql
- models/silver/silver__logs.yml
- models/silver/silver__traces.sql
1. Added tx_gaps test to `silver_logs`
2. Changed unique key to tx_hash in `silver_logs` and `silver_traces`
> AN-2580/unique-key-tx-test

- README.md
- dbt_project.yml
- macros/tags/add_database_or_schema_tags.sql
- macros/tags/snowflake_tagging.sql
- models/sushi/sushi__dim_dex_pools.sql
- models/sushi/sushi__dim_kashi_pairs.sql
- models/sushi/sushi__ez_borrowing.sql
- models/sushi/sushi__ez_lending.sql
- models/sushi/sushi__ez_swaps.sql
1. Implemented Snowflake tags via Macros and Model configs
2. Set `UPDATE_SNOWFLAKE_TAGS: True` and updated `readme.md` accordingly
3. Need to run `dbt run-operation` after merge
4. [Ticket](https://team-1612274056224.atlassian.net/browse/AN-2699?atlOrigin=eyJpIjoiMjBkNWI3ZTUyN2M4NDI4YzkzNDliYzRiOTZkNzExMGYiLCJwIjoiaiJ9)
> AN-2699/snowflake-tags-avalanche

- macros/sp_create_prod_clone.sql
1. Updated `sp_create_prod_clone` with new format/process 
2. Added var to fix issue with snowflake tagging on dev
3. [Ticket](https://team-1612274056224.atlassian.net/browse/AN-2728?atlOrigin=eyJpIjoiYjNiODU0ODFmMDlkNDIxMGI2ZmQ4NTI2MjE5MjkzMjciLCJwIjoiaiJ9)
> AN-2728/dev-tag-fix-avax

- .github/workflows/dbt_docs_update.yml
- .github/workflows/dbt_run_adhoc.yml
- .github/workflows/dbt_run_api_feeder_table.yml
- .github/workflows/dbt_run_dev_refresh.yml
- .github/workflows/dbt_run_incremental.yml
- .github/workflows/dbt_test.yml
1. Modified workflows to reference `environment variables` instead of `secrets` for non-sensitive variables
2. [Ticket](https://team-1612274056224.atlassian.net/browse/AN-2756)
> AN-2756/env-var-update

- models/sushi/sushi__dim_kashi_pairs.yml
- models/sushi/sushi__ez_borrowing.yml
- models/sushi/sushi__ez_lending.yml
1. Added `Deprecating soon` to core sushi model descriptions
2. Removed tests from applicable yml files
> AN-2785/sushi-tests-avax

- .github/workflows/dbt_run_incremental.yml
excludes streamline and decoder models from incremental
> exclude files

- models/doc_descriptions/general/deprecation.md
- models/gold/core__ez_decoded_event_logs.sql
- models/gold/core__ez_decoded_event_logs.yml
- models/gold/core__fact_decoded_event_logs.sql
- models/gold/core__fact_decoded_event_logs.yml
- models/gold/core__fact_event_logs.yml
- models/gold/core__fact_transactions.yml
- adds new decoded tables to gold 
- adds deprecation notice to impacted columns
> gold views and deprecation notices

- .github/workflows/dbt_run_streamline_history.yml
- .github/workflows/dbt_test_daily.yml
- .github/workflows/dbt_test_intraday.yml
- macros/dbt/get_merge_sql.sql
- macros/dbt/get_tmp_relation_type.sql
- macros/lookback.sql
- models/gold/core__ez_avax_transfers.sql
- models/silver/core/silver__logs2.sql
- models/silver/core/silver__receipts.sql
- models/silver/core/silver__traces2.sql
- models/silver/core/silver__transactions2.sql
- models/silver/core/silver__tx_count.sql
- models/silver/core/tests/blocks/test_silver__blocks_recent.sql
- models/silver/core/tests/event_logs/test_silver__logs_recent.sql
- models/silver/core/tests/receipts/test_silver__receipts_recent.sql
- models/silver/core/tests/traces/test_silver__traces_recent.sql
- models/silver/core/tests/transactions/test_silver__transactions_recent.sql
- models/silver/streamline/core/history/streamline__debug_traceBlockByNumber_history.sql
- models/silver/streamline/core/history/streamline__qn_getBlockWithReceipts_history.sql
- models/silver/streamline/core/realtime/streamline__debug_traceBlockByNumber_realtime.sql
- models/silver/streamline/core/realtime/streamline__qn_getBlockWithReceipts_realtime.sql
- packages.yml
- adds 1.4 optimizations
- moves workflows around
> An 3907/dbt 1 4

- .github/workflows/dbt_run_streamline_decoder.yml
- models/gold/core__ez_decoded_event_logs.sql
- models/gold/core__fact_decoded_event_logs.sql
- models/silver/silver__decoded_logs.sql
- models/silver/silver__decoded_logs_full.sql
- models/silver/silver__decoded_logs_full.yml
- adds a second table to join in logs info, 10x performance on views
> Decoded logs table

- macros/tests/tx_gaps.sql
- models/silver/core/silver__logs.sql
- models/silver/core/silver__traces.sql
- models/silver/core/silver__transactions.sql
- tests/avax/test_silver__missing_txs.sql
- tests/avax/test_silver__recent_missing_txs.sql
- refines tx_gap macro test
- moves lookback to join key instead of where
- handles tickets AN-3333 and AN-3332
> tests and lookback

- models/silver/silver__decoded_logs.sql
- update unique key to match `silver__logs`
- removes lookback
> match logs

- models/silver/core/silver__confirmed_blocks.sql
- adds silver model for testing against
> add confirmed blocks model

- models/silver/core/silver__blocks.sql
- models/silver/core/silver__logs.sql
- models/silver/core/silver__receipts.sql
- models/silver/core/silver__traces.sql
- models/silver/core/silver__transactions.sql
- models/silver/dex/curve/silver_dex__curve_pools.sql
- models/silver/dex/curve/silver_dex__curve_swaps.sql
- models/silver/dex/fraxswap/silver_dex__fraxswap_pools.sql
- models/silver/dex/fraxswap/silver_dex__fraxswap_swaps.sql
- models/silver/dex/gmx/silver_dex__gmx_swaps.sql
- models/silver/dex/hashflow/silver_dex__hashflow_swaps.sql
- models/silver/dex/kyberswap/silver_dex__kyberswap_v1_dynamic_pools.sql
- models/silver/dex/kyberswap/silver_dex__kyberswap_v1_dynamic_swaps.sql
- models/silver/dex/kyberswap/silver_dex__kyberswap_v1_static_pools.sql
- models/silver/dex/kyberswap/silver_dex__kyberswap_v1_static_swaps.sql
- models/silver/dex/kyberswap/silver_dex__kyberswap_v2_elastic_pools.sql
- models/silver/dex/kyberswap/silver_dex__kyberswap_v2_elastic_swaps.sql
- models/silver/dex/pangolin/silver_dex__pangolin_pools.sql
- models/silver/dex/pangolin/silver_dex__pangolin_swaps.sql
- models/silver/dex/platypus/silver_dex__platypus_swaps.sql
- models/silver/dex/sushi/silver_dex__sushi_pools.sql
- models/silver/dex/sushi/silver_dex__sushi_swaps.sql
- models/silver/dex/trader_joe/silver_dex__trader_joe_v1_pools.sql
- models/silver/dex/trader_joe/silver_dex__trader_joe_v1_swaps.sql
- models/silver/dex/trader_joe/silver_dex__trader_joe_v2_1_swaps.sql
- models/silver/dex/trader_joe/silver_dex__trader_joe_v2_pools.sql
- models/silver/dex/trader_joe/silver_dex__trader_joe_v2_swaps.sql
- models/silver/dex/woofi/silver_dex__woofi_swaps.sql
- models/silver/silver__contracts.sql
- models/silver/silver__transfers.sql
- Update all models using hex_to_int using `public` or `ethereum.public` schema to `utils` schema
- Excludes models with `enabled = false`
- Was having issues running models with `ALTER TABLE {{ this }} ADD SEARCH OPTIMIZATION` post hook
- After setting all post hooks from `ALTER TABLE {{ this }} ADD SEARCH OPTIMIZATION`  to `""` all models ran successfully
- Did not commit post_hook modifications, only used for testing
> AN-3306/swap-public-to-utils

- models/silver/dex/silver_dex__complete_dex_swaps.sql
- models/silver/dex/uniswap/silver_dex__univ3_pools.sql
- models/silver/dex/uniswap/silver_dex__univ3_pools.yml
- models/silver/dex/uniswap/silver_dex__univ3_swaps.sql
- models/silver/dex/uniswap/silver_dex__univ3_swaps.yml
1. Uni v3 Pools and Swaps models
2. complete_dex_swaps updated accordingly
3. requires `dbt run -m models/silver/dex/uniswap+ --full-refresh`
> AN-3576/uni-v3

- models/silver/dex/hashflow/silver_dex__hashflow_v3_pools.sql
- models/silver/dex/hashflow/silver_dex__hashflow_v3_pools.yml
- models/silver/dex/hashflow/silver_dex__hashflow_v3_swaps.sql
- models/silver/dex/hashflow/silver_dex__hashflow_v3_swaps.yml
- models/silver/dex/silver_dex__complete_dex_swaps.sql
`dbt run -m models/silver/dex/hashflow/silver_dex__hashflow_v3_pools.sql models/silver/dex/hashflow/silver_dex__hashflow_v3_swaps.sql models/silver/dex/silver_dex__complete_dex_swaps.sql models/gold/defi/defi__ez_dex_swaps.sql --full-refresh`
> AN-4087/Add-Hashflow-V3-swaps-and-pools 

- packages.yml
`dbt run -m models/github_actions`
> number format

- models/silver/nft/silver__salvor_sales.yml
changing recency of current salvor contract to 7 days
> change recency to 7

- models/doc_descriptions/general/__overview__.md
- models/doc_descriptions/stats/evm_stats_core.md
- models/gold/stats/stats__ez_core_metrics_hourly.sql
- models/gold/stats/stats__ez_core_metrics_hourly.yml
- models/silver/stats/silver_stats__core_metrics_hourly.sql
- models/silver/stats/silver_stats__core_metrics_hourly.yml
1. Aggregated stats table for core metrics hourly
2. Requires permissions for new schema
`dbt run -m models/silver/stats+ --full-refresh`
> AN-4454/core-stats

- models/bronze/api_udf/bronze_api__token_reads.sql
- models/silver/defi/bridge/stargate/silver_bridge__stargate_createpool.sql
- models/silver/defi/dex/balancer/silver_dex__balancer_pools.sql
- models/silver/defi/dex/curve/silver_dex__curve_pools.sql
- models/sources.yml
- package-lock.yml
- packages.yml
`dbt run -s livequery_models.deploy.core --vars '{DROP_UDFS_AND_SPS: true}' -t prod && dbt run -s livequery_models.deploy.core --vars '{UPDATE_UDFS_AND_SPS: true}' -t prod`
> vault-secrets

- models/silver/defi/dex/silver_dex__complete_dex_liquidity_pools.sql
- models/silver/defi/dex/silver_dex__complete_dex_swaps.sql
- models/silver/defi/dex/uniswap/silver_dex__univ2_pools.sql
- models/silver/defi/dex/uniswap/silver_dex__univ2_pools.yml
- models/silver/defi/dex/uniswap/silver_dex__univ2_swaps.sql
- models/silver/defi/dex/uniswap/silver_dex__univ2_swaps.yml
```
dbt run -m models/silver/defi/dex/uniswap/silver_dex__univ2_pools.sql models/silver/defi/dex/uniswap/silver_dex__univ2_swaps.sql --full-refresh && dbt run -m models/silver/defi/dex/silver_dex__complete_dex_swaps.sql --vars '{"HEAL_CURATED_MODEL":"univ2_swaps"}' && dbt run -m models/gold/defi/defi__dim_dex_liquidity_pools.sql models/gold/defi/defi__ez_dex_swaps.sql --full-refresh
```
> AN-4558/add-univ2-to-all-evms 

- models/gold/nft/nft__ez_nft_sales.yml
- models/silver/nft/sales/silver__complete_nft_sales.sql
- models/silver/nft/sales/silver__complete_nft_sales.yml
- models/silver/nft/sales/silver__seaport_1_6_sales.sql
- models/silver/nft/sales/silver__seaport_1_6_sales.yml
1. Add seaport 1.6
2. turn off recency for seaport 1.5
dbt run -m models/silver/nft/sales/silver__seaport_1_6_sales.sql --full-refresh && dbt run -m models/silver/nft/sales/silver__complete_nft_sales.sql --vars '{"HEAL_CURATED_MODEL":["seaport_1_6"]}'
> Add seaport 1.6

- models/doc_descriptions/transfers/avax_transfer_table_doc.md
- models/doc_descriptions/transfers/evm_transfers_table_doc.md
- models/gold/core/core__ez_native_transfers.yml
- models/gold/core/core__ez_token_transfers.yml
- models/gold/core/core__fact_token_transfers.yml
to capture docs updates in snowflake: `dbt run -m models/gold/core/core__ez_native_transfers.sql models/gold/core/core__ez_token_transfers.sql models/gold/core/core__fact_token_transfers.sql`
> AN-4879/transfers-docs

- models/gold/nft/nft__ez_nft_sales.yml
- models/silver/nft/sales/silver__complete_nft_sales.sql
- models/silver/nft/sales/silver__element_sales.sql
- models/silver/nft/sales/silver__element_sales.yml
- models/silver/nft/sales/silver__joepegs_sales.sql
- models/silver/nft/sales/silver__salvor_sales.sql
- models/silver/nft/sales/silver__seaport_1_1_sales.sql
- models/silver/nft/sales/silver__seaport_1_4_sales.sql
- models/silver/nft/sales/silver__seaport_1_5_sales.sql
- models/silver/nft/sales/silver__seaport_1_6_sales.sql
Add element marketplace to avalanche
`dbt run -m models/silver/NFT/sales/silver__element_sales.sql --full-refresh && dbt run -m models/silver/nft/sales/silver__complete_nft_sales.sql --vars '{"HEAL_MODELS":["element"]}'`
> An 4751/element avax

- .github/workflows/dbt_run_traces_fix.yml
- models/silver/core/silver__fact_traces2.sql
- models/silver/core/traces2_fix/silver__fact_traces2_fix.sql
fix the error logic for fact_traces2 and new data
add model to identify historical data that needs fixing
add workflow to run model in step 2
`dbt run -m models/silver/core/traces2_fix/silver__fact_traces2_fix.sql --full-refresh`
> AN-5669 Add traces2 fix - avalanche

- .github/workflows/dbt_run_traces_fix_dexalot.yml
- models/dexalot/silver/silver_dexalot__fact_traces2.sql
- models/dexalot/silver/traces2_fix/silver_dexalot__fact_traces2_fix.sql
add traces2 fix and workflow
`dbt run -m models/dexalot/silver/traces2_fix/silver_dexalot__fact_traces2_fix.sql --full-refresh`
> AN-5669/traces2-fix-dexalot

- models/silver/defi/bridge/cctp/silver_bridge__cctp_depositforburn.sql
- added unichain as part of evm address conversions
```
dbt seed --select silver_bridge__cctp_chain_id_seed && dbt run -m models/silver/defi/bridge/cctp/silver_bridge__cctp_depositforburn.sql --full-refresh && dbt run -m models/silver/defi/bridge/silver_bridge__complete_bridge_activity.sql --vars '{"HEAL_MODELS":"cctp"}'
```
> add cctp unichain

- models/silver/defi/lending/benqi/silver__benqi_asset_details.sql
`dbt run -m models/silver/defi/lending/benqi --full-refresh && dbt run -m models/silver/defi/lending/complete_lending --vars '{"HEAL_MODELS":"benqi"}'`
> add-new-benqi-asset-type

- models/silver/defi/lending/aave/silver__aave_tokens.sql
`dbt run -m models/silver/defi/lending/aave --full-refresh && dbt run --vars '{"HEAL_MODELS":"aave"}' -m models/silver/defi/lending/complete_lending`
> AN-5443/aave-token-model-updates 

- .github/workflows/dbt_alter_all_gha_tasks.yml
- .github/workflows/dbt_alter_gha_tasks.yml
- .github/workflows/dbt_deploy_new_workflows.yml
- .github/workflows/dbt_docs_update.yml
- .github/workflows/dbt_integration_test.yml
- .github/workflows/dbt_run_adhoc.yml
- .github/workflows/dbt_run_dev_refresh.yml
- .github/workflows/dbt_run_full_observability.yml
- .github/workflows/dbt_run_heal_models.yml
- .github/workflows/dbt_run_scheduled_abis.yml
- .github/workflows/dbt_run_scheduled_curated.yml
- .github/workflows/dbt_run_scheduled_decoder.yml
- .github/workflows/dbt_run_scheduled_dexalot_main.yml
- .github/workflows/dbt_run_scheduled_main.yml
- .github/workflows/dbt_run_scheduled_scores.yml
- .github/workflows/dbt_run_streamline_chainhead.yml
- .github/workflows/dbt_run_streamline_decoder_history.yml
- .github/workflows/dbt_run_streamline_dexalot_chainhead.yml
- .github/workflows/dbt_run_streamline_dexalot_history.yml
- .github/workflows/dbt_run_streamline_history.yml
- .github/workflows/dbt_test_daily.yml
- .github/workflows/dbt_test_intraday.yml
- .github/workflows/dbt_test_monthly.yml
- packages.yml
`dbt run -m main_package.core.gold.core__ez_token_transfers --vars '{"GLOBAL_GOLD_FR_ENABLED":True}' --full-refresh`
> version upgrade

- models/silver/defi/bridge/native/silver_bridge__native_v2.sql
- models/silver/defi/bridge/native/silver_bridge__native_v2.yml
- models/silver/defi/bridge/silver_bridge__complete_bridge_activity.sql
`dbt run -m models/silver/defi/bridge/native/silver_bridge__native_v2.sql --full-refresh && dbt run -m models/silver/defi/bridge/silver_bridge__complete_bridge_activity.sql --vars '{"HEAL_MODELS": ["native_v2"]}'`
> add Avalanche native bridge
